### ISSUE TITLE
unclear on which microcontroller should be used

### ISSUE THREAD

**Issue by landfillbaby** [mattdibi/yampad#2]
"Arduino Pro Micro" isn't a real product
comparing the board here to the images in [this Stack Exchange answer](https://arduino.stackexchange.com/a/47161), it seems you actually meant the Sparkfun Pro Micro, but people may be confused and buy the actual Arduino Micro, which is obviously a different board and wouldn't work for this project without modifications
just thought it would be helpful to clarify

**Comment by mattdibi** [comment]
Hi,

thank you for making me notice this. I never thought this could be misunderstood since the "unofficial" name of the Sparkfun Pro Micro seems to be Arduino Pro Micro (given what I find searching for it on eBay and Aliexpress). I'll make it clearer in the BOM anyway. ;)
