### ISSUE TITLE
SMD or normal wire diodes

### ISSUE THREAD

**Issue by konisteel** [mattdibi/yampad#22]
Hey i plan on making a pcb and is it possible to use normal wire diodes instead of smd ones? Mainly because it's hard to find it and hard to solder it.
Thanks

**Comment by mattdibi** [comment]
Hello there @konisteel!

The PCB available in this repository doesn't support THT diodes (i.e. "wire diodes") only SMD ones.

**Comment by konisteel** [comment]
Can't I solder the wires in the pads? It will still work the same right?
thanks

**Comment by konisteel** [comment]
band the wires and cut them so a little bit is visible and solder that in the pads
![image](https://github.com/user-attachments/assets/b95f8d36-8d00-4454-92c7-c3b7f915204c)

**Comment by konisteel** [comment]
Or maybe i can use these?
![image](https://github.com/user-attachments/assets/9c265049-a94e-4980-94a1-8b07e6cf3705)
i dont know why they look like that lol

**Comment by mattdibi** [comment]
> Can't I solder the wires in the pads? It will still work the same right? thanks

Well yeah, I wouldn't recommend it but it should work.

> Or maybe i can use these?

I think that that's a more exotic form factor than the officially supported one. Are you sure you want to push your luck with those?

The SOD-123 diodes I listed in the part list should be fairly easy to solder by hand...

**Comment by konisteel** [comment]
Well the SOD-123 diodes for 1n4148 is not available in my country only the wire and exotic form factor
if you have extra time maybe you could edit the file to make it fit the wire diodes by adding holes to it?

**Comment by kuro-codes** [comment]
> Well the SOD-123 diodes for 1n4148 is not available in my country only the wire and exotic form factor if you have extra time maybe you could edit the file to make it fit the wire diodes by adding holes to it?

I mean it is open source and you just could add them yourself if you need them.

**Comment by mattdibi** [comment]
I think that 0805 1N4148 diodes should fit inside a SOD-123 footprint and should be readily available everywhere. IIRC I used those for my PCBs. Before purchasing them give it a proper look though.

> if you have extra time maybe you could edit the file to make it fit the wire diodes by adding holes to it?

I'm sorry but I cannot do that currently.

**Comment by konisteel** [comment]
> I think that 0805 1N4148 diodes should fit inside a SOD-123 footprint and should be readily available everywhere. IIRC I used those for my PCBs. Before purchasing them give it a proper look though.
> 
> > if you have extra time maybe you could edit the file to make it fit the wire diodes by adding holes to it?
> 
> I'm sorry but I cannot do that currently.

those also unfortunately are not available. Only wires and those exotic but 1 shop has them and it is double the price of normal ones so not a chance as I plan on building 20 of them
