### ISSUE TITLE
Underglow & capasitors

### ISSUE THREAD

**Issue by konisteel** [mattdibi/yampad#24]
Hey i just realized you used capacitors beside the ws2812b leds. If I don't install the leds than the capacitors are not necessary right?

**Comment by konisteel** [comment]
Or i can use the leds without the capacitors? will it damage the pcb or anything i need to be ware of?

**Comment by konisteel** [comment]
Or can you suggest some other capacitors that i can use? like 104 100nf

![image](https://github.com/user-attachments/assets/b60e6cee-2571-4335-ba7e-ceec0427f730)

**Comment by mattdibi** [comment]
Hi @konisteel,

you're correct: the capacitors are only required if you install the ws2812b leds. I should have put a note in the main readme about this.

**Comment by konisteel** [comment]
Will there be any issues if I use ws2812b leds without the capacitors?

**Comment by mattdibi** [comment]
> Will there be any issues if I use ws2812b leds without the capacitors?

The [datasheet](https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf) application circuit uses them. I would not recommend running them without capacitors but I can't say for sure whether not installing them will introduce any issue. Do it at your own risk 🤷
