### ISSUE TITLE
Spark fun Pro Micro

### ISSUE THREAD

**Issue by GhastlyPompano** [mattdibi/yampad#8]
Sparkfun's ProMicro comes in 2 variations. A 3.3v and a 5v. Which should I be using?

**Comment by mattdibi** [comment]
Hi!

The pre-built firmware supports 5v/16MHz pro micros. If you order the 3.3v/8MHz you just need to change the `rules.mk` file to update [the CPU frequency](https://github.com/mattdibi/qmk_firmware/blob/6923c833ba1d2c0118f93a1a0708f2a898deba3c/keyboards/yampad/rules.mk#L16) and rebuild the firmware.

So, they're all supported but I suggest you to use the 5V version. :)
